### PR TITLE
Remove extra types and improve readme

### PR DESCRIPTION
**Pull request by vitalics**
changes: 
- remove extra types since user see that he can import `Props`, `State` and `Key` type
- remove `ReactComponent` from global
- add a point about typescript and types in readme
- add a point about composite components

### CODE REVIEW

**Comment by vitalics** [comment]
CI Failed tests:
- ReactJS TestCafe plugin (React 16) - Should search inside of portal component
  **Reason**: TypeError: Object doesn't support property or method 'loadApp'
-  ReactJS TestCafe plugin (React 15) - Should get component key 
   **Reason**: (window.loadApp is not a function)
   Unstable function loadApp
- ReactJS TestCafe plugin (the app loads during test) (React 16) - Should search inside of stateless root GH-33
  **Reason**: TypeError: window.loadApp is not a function
  Unstable function loadApp

**Comment by VasilyStrelyaev** [comment]
@vitalics, good job.
 
I just wanted to clarify some terms you used in `README`.
 
In the second section, you are talking about the 'composite' props and state, and show an example where the `State` type uses a different type - `Option`. Is this what makes it 'composite'? Do I get it right that the 'composite' props or state include different types?

**Comment by VasilyStrelyaev** [comment]
Thanks for the clarifications!

@kirovboris, @vitalics, what do you think if we put it this way in `README`:

-----

### TypeScript Generic Selector

Use the generic `ReactComponent` type to create scalable selectors in TypeScript.

Pass the `props` object as the type argument to `ReactComponent` to introduce a type for a specific component.

```ts
type TodoItem = ReactComponent<{ id: string }>;
```

You can then pass the created `TodoItem` type to the `withProps` and `getReact` generic methods.

```ts
const component  = ReactSelector('TodoItem');
type TodoItem    = ReactComponent<{ id: string }>;

const item1  = component.withProps<TodoItem>('id', 'tdi-1');
const itemId = component.getReact<TodoItem>(({ props }) => props.id);
```

**Example**

``` ts
import { ReactSelector, ReactComponent } from 'testcafe-react-selectors';

fixture`typescript support`
    .page('http://react-page-example.com')

test('ReactComponent', async t => {
    const todoList         = ReactSelector('TodoList');
    type TodoListComponent = ReactComponent<{ id: string }>;

    const todoListId = todoList.getReact<TodoListComponent>(({ props }) => props.id);

    await t.expect(todoListId).eql('ul-item');
});
```

#### Composite Types in Props and State

If a component's props and state include other composite types, you can create your own type definitions for them. Then pass these definitions to `ReactComponent` as type arguments.

The following example shows custom `Props` and `State` type definitions. The `State` type uses another composite type - `Option`.

``` ts
import { ReactComponent } from 'testcafe-react-selectors';

interface Props {
    id: string;
    text: string;
}

interface Option {
    id: number;
    title: string;
    description: string;
}

interface State {
    optionsCount: number;
    options: Option[];
}

export type OptionReactComponent = ReactComponent<Props, State>;
```

**Comment by kirovboris** [comment]
Published `testcafe-react-selectors@3.0.3`

**Pull request merged**
