### PR TITLE
Added the partial objects matching (#98)

### PR DESCRIPTION
**Pull request by kirovboris**
/cc @VasilyStrelyaev,
check the strings and the option name, please

### CODE REVIEW

**Comment by VasilyStrelyaev** [comment]
The correctors don't approve `but it was` anymore :(

**Comment by VasilyStrelyaev** [comment]
> check the strings and the option name, please

Are there more option names to check other than `exactObjectMatch`

**Comment by kirovboris** [comment]
No, just `exactObjectMatch`.

**Comment by kirovboris** [comment]
FPR

**Pull request merged**
